const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.EightDir.Exps.VectorX,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Text.Acts.SetVisible
	];
};
self.C3_JsPropNameTable = [
	{"8Direction": 0},
	{ScrollTo: 0},
	{Character: 0},
	{Solid: 0},
	{Brick: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{CharacterBullet: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Pathfinding: 0},
	{Enemy: 0},
	{EnemyBullet: 0},
	{Colletible: 0},
	{Door: 0},
	{Sine: 0},
	{Boss: 0},
	{Pass: 0},
	{BossBullet: 0},
	{BossHadoukenTeleguiado: 0},
	{Text: 0},
	{Aim: 0},
	{life: 0},
	{Enemy2Count: 0},
	{EnemyCount: 0},
	{ColletibleCount: 0},
	{BossHP: 0}
];

self.InstanceType = {
	Character: class extends self.ISpriteInstance {},
	Brick: class extends self.ISpriteInstance {},
	CharacterBullet: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Enemy: class extends self.ISpriteInstance {},
	EnemyBullet: class extends self.ISpriteInstance {},
	Colletible: class extends self.ISpriteInstance {},
	Door: class extends self.ISpriteInstance {},
	Boss: class extends self.ISpriteInstance {},
	Pass: class extends self.ISpriteInstance {},
	BossBullet: class extends self.ISpriteInstance {},
	BossHadoukenTeleguiado: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Aim: class extends self.ISpriteInstance {}
}